# Generated by Django 5.0.6 on 2024-06-25 22:50

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('first_name', models.CharField(max_length=100, verbose_name='firstName')),
                ('gender', models.CharField(max_length=6, verbose_name='gender')),
                ('profile', models.CharField(max_length=25, verbose_name='profile')),
                ('domain', models.CharField(max_length=100, verbose_name='domain')),
                ('activity', models.CharField(max_length=80, verbose_name='activity')),
                ('biography', models.TextField(blank=True, null=True, verbose_name='biography')),
                ('email', models.EmailField(max_length=254)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='profiles', verbose_name='profile image')),
            ],
        ),
        migrations.CreateModel(
            name='Entrepreneur',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='sireiapp.person')),
                ('phone_number', models.CharField(max_length=30, verbose_name='phone number')),
                ('project_file', models.FileField(blank=True, null=True, upload_to='projects', verbose_name='project file')),
            ],
            bases=('sireiapp.person',),
        ),
        migrations.CreateModel(
            name='Investor',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='sireiapp.person')),
                ('experience_year', models.IntegerField(verbose_name='experience year')),
            ],
            bases=('sireiapp.person',),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='content')),
                ('date_send', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='sireiapp.person')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='content')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message', to='sireiapp.person')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('sector', models.CharField(max_length=255, verbose_name='sector')),
                ('description', models.TextField(verbose_name='description')),
                ('published', models.DateTimeField(auto_now_add=True, verbose_name='published')),
                ('is_available', models.BooleanField(default=True, verbose_name='is available')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project', to='sireiapp.entrepreneur')),
            ],
        ),
    ]
