# Generated by Django 5.0.6 on 2024-06-25 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sireiapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='email',
        ),
    ]
