# Generated by Django 5.0.6 on 2024-06-25 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sireiapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='biography',
            field=models.TextField(blank=True, null=True, verbose_name='biography'),
        ),
        migrations.AlterField(
            model_name='person',
            name='gender',
            field=models.CharField(choices=[('homme', 'femme')], max_length=5, verbose_name='gender'),
        ),
        migrations.AlterField(
            model_name='person',
            name='profile',
            field=models.CharField(choices=[('entrepreneur', 'investisseur')], max_length=20, verbose_name='profile'),
        ),
    ]
