# Generated by Django 5.0.6 on 2024-06-26 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sireiapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WaitingEntrepreneur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('first_name', models.CharField(max_length=100, verbose_name='firstName')),
                ('gender', models.CharField(max_length=6, verbose_name='gender')),
                ('profile', models.CharField(max_length=25, verbose_name='profile')),
                ('domain', models.CharField(max_length=100, verbose_name='domain')),
                ('activity', models.CharField(max_length=80, verbose_name='activity')),
                ('biography', models.TextField(blank=True, null=True, verbose_name='biography')),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='profiles', verbose_name='profile image')),
                ('phone_number', models.CharField(max_length=30, verbose_name='phone number')),
                ('project_file', models.FileField(blank=True, null=True, upload_to='projects', verbose_name='project file')),
            ],
        ),
        migrations.CreateModel(
            name='WaitingInvestor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('first_name', models.CharField(max_length=100, verbose_name='firstName')),
                ('gender', models.CharField(max_length=6, verbose_name='gender')),
                ('profile', models.CharField(max_length=25, verbose_name='profile')),
                ('domain', models.CharField(max_length=100, verbose_name='domain')),
                ('activity', models.CharField(max_length=80, verbose_name='activity')),
                ('biography', models.TextField(blank=True, null=True, verbose_name='biography')),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='profiles', verbose_name='profile image')),
                ('experience_year', models.IntegerField(verbose_name='experience year')),
            ],
        ),
    ]
