# Generated by Django 5.0.6 on 2024-06-26 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sireiapp', '0002_waitingentrepreneur_waitinginvestor'),
    ]

    operations = [
        migrations.AddField(
            model_name='waitingentrepreneur',
            name='email',
            field=models.EmailField(default='', max_length=254, verbose_name='email'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='waitinginvestor',
            name='email',
            field=models.EmailField(default='', max_length=254, verbose_name='email'),
            preserve_default=False,
        ),
    ]
