# Generated by Django 5.0.6 on 2024-06-25 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sireiapp', '0002_alter_person_biography_alter_person_gender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='gender',
            field=models.CharField(choices=[('homme', 'femme')], max_length=6, verbose_name='gender'),
        ),
        migrations.AlterField(
            model_name='person',
            name='profile',
            field=models.CharField(choices=[('entrepreneur', 'investisseur')], max_length=25, verbose_name='profile'),
        ),
    ]
