# Generated by Django 5.0.6 on 2024-06-25 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sireiapp', '0003_alter_person_gender_alter_person_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrepreneur',
            name='project_file',
            field=models.FileField(blank=True, null=True, upload_to='projects', verbose_name='project file'),
        ),
        migrations.AddField(
            model_name='person',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='profiles', verbose_name='profile image'),
        ),
        migrations.AlterField(
            model_name='person',
            name='gender',
            field=models.CharField(max_length=6, verbose_name='gender'),
        ),
        migrations.AlterField(
            model_name='person',
            name='profile',
            field=models.CharField(max_length=25, verbose_name='profile'),
        ),
    ]
